### ISSUE TITLE
[Tracking] fully extract `forc-explore` from `sway`

### ISSUE THREAD

**Issue by spiral-ladder** [FuelLabs/forc-explorer#1]
- [x] copy `forc-explore` from `sway`  #3
- [x] CI: basic CI for testing, publishing, etc. #4
- [x] CI (nightly): include a nightly release step within `sway-nightly-binaries` 
- [x] sway: remove `forc-explore` plugin entirely https://github.com/FuelLabs/sway/issues/2609
- [x] sway: remove `forc-explore` publishing step https://github.com/FuelLabs/sway/issues/2609

**Comment by spiral-ladder** [comment]
Since [sway#2609](https://github.com/FuelLabs/sway/issues/2609) is closed, this can be closed now.
